### ISSUE TITLE
Uber Trap doesn't account for Toons with less than 15 laff points.

### ISSUE THREAD

**Issue by BeastnodeG** [DevvyDont/toontown-archipelago#28]
For yamls that have a starting laff of >15 the uber trap actually acts more as a full heal. Setting the player's current laff points above their current laff point maximum. (a toon with a 5 laff maximum could have their current laff set to 15)
Additionally, if a player ever falls below 15 laff by "normal means," and receives an uber trap, they will instead recover up to 15 laff points.

The Uber Trap should account for these cases either by setting a Toons laff to 1 laff point, for more compatibility, or by having an alternative effect while a toon is at or below 15 laff points.

**Comment by DevvyDont** [comment]
addressed in 08fb71d
